language: julia

before_install:
  - sudo apt-get -y install patchelf
  
os:
  - linux

julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      os: linux
      before_script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/KristofferC/JuAFEM.jl.git", rev="master"))'
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build()'
        - julia --project=docs/ docs/make.jl
      after_success:
        - julia --project=docs/ docs/deploy.jl

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/KristofferC/JuAFEM.jl.git", rev="master"))'
